// File generated by FlutterFire CLI configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqk9XHXONs5l8C8gjXGyJUFWc30ivWHJ0',
    authDomain: 'sayedgolf-edeff.firebaseapp.com',
    projectId: 'sayedgolf-edeff',
    storageBucket: 'sayedgolf-edeff.firebasestorage.app',
    messagingSenderId: '5568704054',
    appId: '1:5568704054:web:sayedgolf',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqk9XHXONs5l8C8gjXGyJUFWc30ivWHJ0',
    appId: '1:5568704054:android:4ef0bc42564282ae0bf297',
    messagingSenderId: '5568704054',
    projectId: 'sayedgolf-edeff',
    storageBucket: 'sayedgolf-edeff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqk9XHXONs5l8C8gjXGyJUFWc30ivWHJ0',
    appId: '1:5568704054:ios:16870d92c77b7b000bf297',
    messagingSenderId: '5568704054',
    projectId: 'sayedgolf-edeff',
    storageBucket: 'sayedgolf-edeff.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqk9XHXONs5l8C8gjXGyJUFWc30ivWHJ0',
    appId: '1:5568704054:ios:16870d92c77b7b000bf297',
    messagingSenderId: '5568704054',
    projectId: 'sayedgolf-edeff',
    storageBucket: 'sayedgolf-edeff.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqk9XHXONs5l8C8gjXGyJUFWc30ivWHJ0',
    appId: '1:5568704054:windows:sayedgolf',
    messagingSenderId: '5568704054',
    projectId: 'sayedgolf-edeff',
    storageBucket: 'sayedgolf-edeff.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAqk9XHXONs5l8C8gjXGyJUFWc30ivWHJ0',
    appId: '1:5568704054:linux:sayedgolf',
    messagingSenderId: '5568704054',
    projectId: 'sayedgolf-edeff',
    storageBucket: 'sayedgolf-edeff.firebasestorage.app',
  );
}
